# Generated by Django 4.2.4 on 2023-08-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_alter_servico_protocole'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='identificador',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='categoriamanutencao',
            name='titulo',
            field=models.CharField(choices=[('TVM', 'Trocar válvula do motor'), ('TO', 'Troca de óleo'), ('B', 'Balanceamento'), ('TM', 'Trocar Motor'), ('TP', 'Trocar Pneu'), ('CM', 'Trocar caixa de marcha'), ('P', 'PINTAR O CARRO'), ('D', 'Desamassar'), ('A', 'Alinhamento')], max_length=3),
        ),
    ]
