# Generated by Django 4.2.4 on 2023-08-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='Cliente',
            new_name='cliente',
        ),
    ]
